spring:

  application:

    name: Reva-gateway-server

zuul:

  prefix: /reva

  routes:

    associates:

      path: /as/**

      service-id: Associate-Service

    transfers:

      path: /ts/**

      service-id: Transfer-Service 
    enrollments:
    
      path: /rg/**

      service-id: Registration-Service 
server:

  port: 9001

eureka:

  client:

    service-url:

      defaultZone: http://localhost:9999/eureka/

  instance:

    lease-expiration-duration-in-seconds: 2

    lease-renewal-interval-in-seconds: 1

